simulation_params:
  seed: 287225234780671568656474727126864502005
  iterations: 2

landmarks:
  prior_landmarks:
    - [1.5, 0.0]
  landmarks_per_bunch: 3

noise:
  obs_std: 0.7
  obs_range: 2.0
  detection_range: 1.0
  action_std: 0.2
  initial_std: 0.1

planning:
  planning_horizon: 2
  state_samples: 200
  kappa: [0.5, 1.0]
  discount_factor: 0.95
  information_weight: 0.8
  action_partitions: 4
  action_radius: 1.0
  obs_samples: 20

stopping:
  stopping_condition: "max_steps"
  goal: [10.0, 0.0]
  max_steps: 4
  timeout: 10
